### ISSUE TITLE
Allow submitting multiple files

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#1165]
This would require a ~~couple of~~ few related changes.

- [x] create a database migration for `submissions.solution`
- [x] create a rake task to duplicate existing data (`code` + `filename`) into the new `solution` field
- [x] update the controller to save the incoming submission to the current fields (`code` + `filename`) as well as to the `solution` field as a hash of `{filename => code}`
- [x] deploy and run migrations
- [x] update the site to always display code using the new `solutions` field.
- [x] loop through solutions to show all files (not just the first)
- [x] update the controller to be able to accept submissions _either_ using the old format, _or_ in the new format.
- [x] update the `restore` endpoint in the API to return both formats, using only the solutions field
- [x] update the CLI to submit multiple files (see https://github.com/exercism/cli/issues/35)
- [x] remove the code that references `submission.code` and `submission.filename`
- [x] add a database migration to drop the `code` and `filename` fields

We will need to be able to support CLIs that handle the old format for a while yet.

**Comment by kytrinyx** [comment]
@LNA It looks like the very last piece to this is to update the code that sends solutions to the `exercism restore` command.

The sinatra endpoint is defined in `lib/api/routes/iterations.rb`, it's confusingly called "/iterations/latest". The line that points to the view is `pg :iterations, locals: {submissions: submissions}`, so it's using a petroglyph template called `iterations`, which means the view is in `lib/api/views/iterations.pg`. (Petroglyph is a ruby DSL that builds up JSON).

There's a test for this behavior in `test/api/iterations_test.rb`.

This endpoint needs to use `submission.solution` instead of `submission.filename` and `submission.code`.

After that the only change left is to create a migration to drop the old `filename` and `code` fields, and delete any leftover rake tasks that had to do with this.

**Comment by LNA** [comment]
Okay! I'll work on it this upcoming Friday.

**Comment by kytrinyx** [comment]
:sparkles: Thanks!

**Comment by LNA** [comment]
Hello! 

I took a look at the petroglyph documentation, and made the changes in the current implementation at `lib/api/views/iterations.pg` .  Next, I'd like to see where the change is happening in the front end.  Where should I navigate to? localhost:/4567/whereShouldIGo?

**Comment by kytrinyx** [comment]
This is an API endpoint that the client uses. There are a couple of them that use the `iterations.pg`.

You'll need one of the seed user's api keys. In the "assume" menu of the nav bar, pick someone who is listed as either "submitted" or "onboarded". Go to http://localhost:4567/account and grab their api key.

Then visit http://localhost:4567/api/v1/iterations/latest?key=THE_API_KEY

That will show you the JSON output from the api endpoint.

**Comment by LegalizeAdulthood** [comment]
@kytrinyx Nice use of github checklists!

**Comment by LNA** [comment]
It looks like I'll have to update 'test/api/iterations_test.rb' .  I'll shoot you an email on my progress!

**Comment by kytrinyx** [comment]
@LNA I know you've been busy with the whole "change everything" project. I went ahead and implemented the last change so that the `restore` command will work. I'll probably do the cleanup in the next few days, unless you beat me to it.

> add a database migration to drop the code and filename fields

To create a new migration, use the `rake db:generate:migration name=the_name_of_your_migration` command.

**Comment by LNA** [comment]
@kytrinyx indeed! Yesterday was a great first day.  I'm not sure what this week will look like, but I'm positive that I can set aside a block of  time Saturday afternoon to wrap up this story.

**Comment by kytrinyx** [comment]
Excellent! Let me know what you need from me. I'll take a moment to review as well, to make sure we haven't missed anything.

**Comment by LNA** [comment]
Hi @kytrinyx ! Looks like I won't have enough time to finish up this story.  I did some digging around, and the primary thing that needs to happen when submission.code and submission.filename are being removed it to update the tests.  Hopefully I'll be able to contribute more to the project once I get settled at Avant.  :8ball:

**Comment by kytrinyx** [comment]
Hi @LNA, thanks so much for all your work on this! I'll go ahead and do the final cleanup. It looks like it's pretty close :)

**Comment by searls** [comment]
Yay!
