### ISSUE TITLE
Introduce watermarks for "read" status in activity streams

### ISSUE THREAD

**Issue by kytrinyx** [exercism/exercism.io#3130]
We keep track of when you look at a solution in order to be able to mark read/unread status in the activity stream. This has caused an explosion of data (https://github.com/exercism/discussions/issues/15) and also means that when you mark all as read you flood the inbox (#2539).

We're using the _Heroku Postgres **Basic**_, which has a limit of 10 million rows. Heroku is sponsoring us with platform credits, so we can upgrade... however that means taking the site down, and I need to have the time and mental resources to make sure that the upgrade goes smoothly. I haven't had that yet.

The current status of our database usage is 9438126 out of 10000000 rows. In other words, dangerously close to the limit.

A _watermark_ feature will allow us to set a timestamp where everything in a stream that was updated before that timestamp will be marked as read.

We can do two things with this:
1. implement "mark all as read" by setting the watermark to _now_.
2. routinely sweep the views table to find the oldest unviewed item in a track/exercise stream, set the watermark to a moment before it, and then delete the older view rows for solutions of that exercise.

I'm currently working on the following tasks:
- [x] refactor stream tests (PR: #3141) and code (PR: #3142)
- [x] add a watermarks table (PR: #3131)
- [x] read from both the watermarks table and the views table to determine the read/unread status of items in the activity streams (PR: #3143)
- [x] write to the watermarks table on "mark all as read" (PR: #3146)

We will also need to write the following sweeper tasks:
- [ ] delete all view rows that are older than a watermark (#3155)
- [ ] set a watermark based on the oldest unread item of a track+exercise combination

**Comment by bernardoamc** [comment]
I can start coding the `delete all view rows that are older than a watermark`. It is going to be a rake task that is run from time to time, right?

**Comment by kytrinyx** [comment]
@bernardoamc: Yes, a rake task would be perfect. Let me share a gist with some stuff I wrote that may or may not help.

**Comment by kytrinyx** [comment]
OK here you go: https://gist.github.com/kytrinyx/3eb0430908ed42d5882ebc1f6401deb9 (repeating the warning that this may be completely useless)

**Comment by bernardoamc** [comment]
Pretty sure it will help, thank you! Probably going to start this around Monday. ;)

**Comment by kytrinyx** [comment]
@bernardoamc Excellent. I hope to have the basic watermark functionality done by then.

**Comment by bernardoamc** [comment]
@kytrinyx Awesome! Don't hesitate to ping me in future PRs if you need someone to take a look at it.

**Comment by kytrinyx** [comment]
Thanks @bernardoamc, I will!

**Comment by bernardoamc** [comment]
This is a delete query for a `mark all as read`, right? I think we can remove the `user_exercises` table from the query in case of a `mark all from this track as read` or `mark all from this track's problem` as read. Makes sense?

**Comment by kytrinyx** [comment]
> This is a delete query for a mark all as read, right? 

@bernardoamc mark all as read doesn't delete any rows, it just creates and updates watermarks. The deletion would happen in the sweeper task.

Based on your question I realized that what I want is `v.last_viewed_at` not `ex.last_activity_at`. So maybe:

```
DELETE FROM views v
USING user_exercises ex, watermarks w
WHERE v.user_id= ?
AND w.user_id=v.user_id
AND v.exercise_id=ex.id
AND w.track_id=ex.language
AND w.slug=ex.slug
AND v.last_viewed_at < w.at;
```

Views only have exercise_id, not track_id and slug, so we need the user_exercise as an intermediary to find the track_id and slug with which we can find the related watermark.

**Comment by bernardoamc** [comment]
Yes, you are absolutely right! 👍

**Comment by bernardoamc** [comment]
Sorry but I'm not going to be able to work on this like I would, just saying this so you can pick any task you want without fearing conflicts. :/

**Comment by kytrinyx** [comment]
:heart: thanks for the heads up @bernardoamc!

**Comment by kytrinyx** [comment]
This is solved, as far as I can tell.
